### ISSUE TITLE
【Bug-editor】editor里应该禁止输入JS文件

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/keepwork#1725]
### Details:

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/d8643349-e3e1-4d83-9b74-92edaa763112)

**Comment by LiXizhi** [comment]
is there a safe sandbox environment for inline css and js?   
So that all js operations are restricted to a given DIV element. 

This can be useful to use keepwork to teach HTML5 programming.  Moreover, we may add some effect like 

![image](https://user-images.githubusercontent.com/94537/44637101-e8024a00-a9e1-11e8-9666-956e380f33cb.png)

**Comment by leopoldchen** [comment]
https://medium.com/zendesk-engineering/sandboxing-javascript-e4def55e855e

**Comment by leopoldchen** [comment]
以白名单的形式，只允许某些个网站使用js
